- hosts: slave-1,slave-2
  tasks:
          - template:
                  src: /ws1/ws1.1/kube_slave.txt
                  dest:  /etc/sysctl.d/k8s.conf


          - command: "sysctl --system"
          - script:
                  cmd: /ws1/ws1.1/join2.txt
